name: Delete news
description: |
  This GitHub Actions workflow calls a delete news every day to fetch and save news articles.

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  call-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call delete news
        run: |
          curl -X POST ${{ secrets.DELETE_URL }} \
            -H "Authorization: Bearer ${{ secrets.KEY }}" \
            -H "Content-Type: application/json"
